/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.93
 * Generated at: 2023-12-07 07:24:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/header.jsp", Long.valueOf(1699358942519L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("        <title>JSP Page</title>\n");
      out.write("        <meta charset=\"utf-8\">\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("        <link href=\"css/header.css\" rel=\"stylesheet\">\n");
      out.write("        <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("        <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js\"></script>\n");
      out.write("        <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css\">\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("        <header class=\"header\">\n");
      out.write("            <a href=\"index.jsp\" class=\"logo\">Developer</a>\n");
      out.write("            <nav class=\"nav-items\">\n");
      out.write("                <a href=\"learning\">Learning</a>\n");
      out.write("                <a href=\"#\">Training</a>\n");
      out.write("                <a href=\"#\">Contact</a> \n");
      out.write("                <div class=\"input-group\">\n");
      out.write("                    <form action=\"search\" method=\"post\" style=\"display: flex;\">\n");
      out.write("                        <input class=\"form-control border-end-0 border rounded-pill\" type=\"text\" placeholder=\"search\" id=\"example-search-input\" name=\"search\">\n");
      out.write("                        <span class=\"input-group-append\">\n");
      out.write("                            <button class=\"btn btn-outline-secondary bg-white border-start-0 border rounded-pill ms-n3\" type=\"submit\">\n");
      out.write("                                <i class=\"fa fa-search\"></i>\n");
      out.write("                            </button>\n");
      out.write("                        </span>\n");
      out.write("                    </form>\n");
      out.write("                </div>\n");
      out.write("            </nav>\n");
      out.write("\n");
      out.write("            <nav class=\"nav-items\">\n");
      out.write("                <!-- Use JSTL to conditionally render the menu -->\n");
      out.write("                ");

                    Boolean isLogIn = (Boolean) session.getAttribute("isLogIn");
                    if (isLogIn != null && isLogIn) {
      out.write("\n");
      out.write("                <div class=\"dropdown dropstart text-end\">\n");
      out.write("                    <button type=\"button\" class=\"btn btn-primary dropdown-toggle\" data-bs-toggle=\"dropdown\">\n");
      out.write("                        User\n");
      out.write("                    </button>\n");
      out.write("                    <ul class=\"dropdown-menu\">\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"profile\">My profile</a></li>\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"update\">Change my profile</a></li>\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"#\">My course</a></li>\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"cart.jsp\">My cart</a></li>\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"logout\">Logout</a></li>\n");
      out.write("                    </ul>\n");
      out.write("                </div>\n");
      out.write("                ");
 } else {
      out.write("\n");
      out.write("                <!-- Login and Register buttons for non-logged-in users -->\n");
      out.write("                <div>\n");
      out.write("                    <form>\n");
      out.write("                        <button type=\"submit\" name=\"button\" value=\"Login\" class=\"btn btn-login\" formaction=\"login2.jsp\">Login</button>\n");
      out.write("                        <button type=\"submit\" name=\"button\" value=\"Register\" class=\"btn btn-danger\" formaction=\"register.jsp\">Register</button>\n");
      out.write("                    </form>\n");
      out.write("                </div>\n");
      out.write("                ");
 }
                
      out.write("\n");
      out.write("            </nav>\n");
      out.write("        </header>\n");
      out.write("    </body>\n");
      out.write("</html>\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("    <head>\n");
      out.write("        <meta charset=\"UTF-8\">\n");
      out.write("        <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("        <title>Simple HTML HomePage</title>\n");
      out.write("        <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css\">\n");
      out.write("        <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\" \n");
      out.write("              integrity=\"sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN\" crossorigin=\"anonymous\">\n");
      out.write("        <style>\n");
      out.write("            @import url('https://fonts.googleapis.com/css2?family=Sriracha&display=swap');\n");
      out.write("\n");
      out.write("            body {\n");
      out.write("                margin: 0;\n");
      out.write("                box-sizing: border-box;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            /* CSS for main element */\n");
      out.write("            .intro {\n");
      out.write("                display: flex;\n");
      out.write("                flex-direction: column;\n");
      out.write("                justify-content: center;\n");
      out.write("                align-items: center;\n");
      out.write("                width: 100%;\n");
      out.write("                height: 520px;\n");
      out.write("                background: linear-gradient(to bottom, rgba(0, 0, 0, 0.5) 0%, rgba(0, 0, 0, 0.5) 100%), url(\"https://images.unsplash.com/photo-1587620962725-abab7fe55159?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1031&q=80\");\n");
      out.write("                background-size: cover;\n");
      out.write("                background-position: center;\n");
      out.write("                background-repeat: no-repeat;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            .intro h1 {\n");
      out.write("                font-family: sans-serif;\n");
      out.write("                font-size: 60px;\n");
      out.write("                color: #fff;\n");
      out.write("                font-weight: bold;\n");
      out.write("                text-transform: uppercase;\n");
      out.write("                margin: 0;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            .intro p {\n");
      out.write("                font-size: 20px;\n");
      out.write("                color: #d1d1d1;\n");
      out.write("                text-transform: uppercase;\n");
      out.write("                margin: 20px 0;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            .intro button {\n");
      out.write("                background-color: #5edaf0;\n");
      out.write("                color: #000;\n");
      out.write("                padding: 10px 25px;\n");
      out.write("                border: none;\n");
      out.write("                border-radius: 5px;\n");
      out.write("                font-size: 20px;\n");
      out.write("                font-weight: bold;\n");
      out.write("                cursor: pointer;\n");
      out.write("                box-shadow: 0px 0px 20px rgba(255, 255, 255, 0.4)\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            .achievements {\n");
      out.write("                display: flex;\n");
      out.write("                justify-content: space-around;\n");
      out.write("                align-items: center;\n");
      out.write("                padding: 40px 80px;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            .achievements .work {\n");
      out.write("                display: flex;\n");
      out.write("                flex-direction: column;\n");
      out.write("                justify-content: center;\n");
      out.write("                align-items: center;\n");
      out.write("                padding: 0 40px;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            .achievements .work i {\n");
      out.write("                width: fit-content;\n");
      out.write("                font-size: 50px;\n");
      out.write("                color: #333333;\n");
      out.write("                border-radius: 50%;\n");
      out.write("                border: 2px solid #333333;\n");
      out.write("                padding: 12px;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            .achievements .work .work-heading {\n");
      out.write("                font-size: 20px;\n");
      out.write("                color: #333333;\n");
      out.write("                text-transform: uppercase;\n");
      out.write("                margin: 10px 0;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            .achievements .work .work-text {\n");
      out.write("                font-size: 15px;\n");
      out.write("                color: #585858;\n");
      out.write("                margin: 10px 0;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            .about-me {\n");
      out.write("                display: flex;\n");
      out.write("                justify-content: center;\n");
      out.write("                align-items: center;\n");
      out.write("                padding: 40px 80px;\n");
      out.write("                border-top: 2px solid #eeeeee;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            .about-me img {\n");
      out.write("                width: 500px;\n");
      out.write("                max-width: 100%;\n");
      out.write("                height: auto;\n");
      out.write("                border-radius: 10px;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            .about-me-text h2 {\n");
      out.write("                font-size: 30px;\n");
      out.write("                color: #333333;\n");
      out.write("                text-transform: uppercase;\n");
      out.write("                margin: 0;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            .about-me-text p {\n");
      out.write("                font-size: 15px;\n");
      out.write("                color: #585858;\n");
      out.write("                margin: 10px 0;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            /* CSS for footer */\n");
      out.write("            .footer {\n");
      out.write("                display: flex;\n");
      out.write("                justify-content: space-between;\n");
      out.write("                align-items: center;\n");
      out.write("                background-color: #302f49;\n");
      out.write("                padding: 40px 80px;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            .footer .copy {\n");
      out.write("                color: #fff;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            .bottom-links {\n");
      out.write("                display: flex;\n");
      out.write("                justify-content: space-around;\n");
      out.write("                align-items: center;\n");
      out.write("                padding: 40px 0;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            .bottom-links .links {\n");
      out.write("                display: flex;\n");
      out.write("                flex-direction: column;\n");
      out.write("                justify-content: center;\n");
      out.write("                align-items: center;\n");
      out.write("                padding: 0 40px;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            .bottom-links .links span {\n");
      out.write("                font-size: 20px;\n");
      out.write("                color: #fff;\n");
      out.write("                text-transform: uppercase;\n");
      out.write("                margin: 10px 0;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            .bottom-links .links a {\n");
      out.write("                text-decoration: none;\n");
      out.write("                color: #a1a1a1;\n");
      out.write("                padding: 10px 20px;\n");
      out.write("            }\n");
      out.write("        </style>\n");
      out.write("    </head>\n");
      out.write("\n");
      out.write("    <body>\n");
      out.write("        <main>\n");
      out.write("            <div class=\"intro\">\n");
      out.write("                <h1>Learn to code</h1>\n");
      out.write("                <p>I am a developer and I love to share code tutorials .</p>\n");
      out.write("                <button>Start now</button>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"achievements\">\n");
      out.write("                <div class=\"work\">\n");
      out.write("                    <i class=\"fas fa-atom\"></i>\n");
      out.write("                    <p class=\"work-heading\">Projects</p>\n");
      out.write("                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n");
      out.write("                        tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud\n");
      out.write("                        exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat..</p>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"work\">\n");
      out.write("                    <i class=\"fas fa-skiing\"></i>\n");
      out.write("                    <p class=\"work-heading\">Skills</p>\n");
      out.write("                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n");
      out.write("                        tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud\n");
      out.write("                        exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat..</p>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"work\">\n");
      out.write("                    <i class=\"fas fa-ethernet\"></i>\n");
      out.write("                    <p class=\"work-heading\">Network</p><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n");
      out.write("                        tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud\n");
      out.write("                        exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat..</p>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"about-me\">\n");
      out.write("                <div class=\"about-me-text\">\n");
      out.write("                    <h2>About Me</h2>\n");
      out.write("                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n");
      out.write("                        tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud\n");
      out.write("                        exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat..</p>\n");
      out.write("                </div>\n");
      out.write("                <img src=\"picture/driving.png\" alt=\"me\">\n");
      out.write("            </div>\n");
      out.write("        </main>\n");
      out.write("        <footer class=\"footer\">\n");
      out.write("            <div class=\"copy\">&copy; 2023 Developer</div>\n");
      out.write("            <div class=\"bottom-links\">\n");
      out.write("                <div class=\"links\">\n");
      out.write("                    <span>More Info</span>\n");
      out.write("                    <a href=\"home.jsp\">Home</a>\n");
      out.write("                    <a href=\"#\">About</a>\n");
      out.write("                    <a href=\"#\">Contact</a>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"links\">\n");
      out.write("                    <span>Social Links</span>\n");
      out.write("                    <a href=\"https://www.facebook.com/quy.nguyenduy.94849/\"><i class=\"fab fa-facebook\"></i></a>\n");
      out.write("                    <a href=\"https://twitter.com/Qu42684846\"><i class=\"fab fa-twitter\"></i></a>\n");
      out.write("                    <a href=\"https://github.com/NDuyQuy?tab=repositories\"><i class=\"fab fa-github\"></i></a>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </footer>\n");
      out.write("    </body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
