/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.93
 * Generated at: 2023-12-07 07:24:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login2_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/header.jsp", Long.valueOf(1699358942519L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("        <title>JSP Page</title>\n");
      out.write("        <meta charset=\"utf-8\">\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("        <link href=\"css/header.css\" rel=\"stylesheet\">\n");
      out.write("        <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("        <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js\"></script>\n");
      out.write("        <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css\">\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("        <header class=\"header\">\n");
      out.write("            <a href=\"index.jsp\" class=\"logo\">Developer</a>\n");
      out.write("            <nav class=\"nav-items\">\n");
      out.write("                <a href=\"learning\">Learning</a>\n");
      out.write("                <a href=\"#\">Training</a>\n");
      out.write("                <a href=\"#\">Contact</a> \n");
      out.write("                <div class=\"input-group\">\n");
      out.write("                    <form action=\"search\" method=\"post\" style=\"display: flex;\">\n");
      out.write("                        <input class=\"form-control border-end-0 border rounded-pill\" type=\"text\" placeholder=\"search\" id=\"example-search-input\" name=\"search\">\n");
      out.write("                        <span class=\"input-group-append\">\n");
      out.write("                            <button class=\"btn btn-outline-secondary bg-white border-start-0 border rounded-pill ms-n3\" type=\"submit\">\n");
      out.write("                                <i class=\"fa fa-search\"></i>\n");
      out.write("                            </button>\n");
      out.write("                        </span>\n");
      out.write("                    </form>\n");
      out.write("                </div>\n");
      out.write("            </nav>\n");
      out.write("\n");
      out.write("            <nav class=\"nav-items\">\n");
      out.write("                <!-- Use JSTL to conditionally render the menu -->\n");
      out.write("                ");

                    Boolean isLogIn = (Boolean) session.getAttribute("isLogIn");
                    if (isLogIn != null && isLogIn) {
      out.write("\n");
      out.write("                <div class=\"dropdown dropstart text-end\">\n");
      out.write("                    <button type=\"button\" class=\"btn btn-primary dropdown-toggle\" data-bs-toggle=\"dropdown\">\n");
      out.write("                        User\n");
      out.write("                    </button>\n");
      out.write("                    <ul class=\"dropdown-menu\">\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"profile\">My profile</a></li>\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"update\">Change my profile</a></li>\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"#\">My course</a></li>\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"cart.jsp\">My cart</a></li>\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"logout\">Logout</a></li>\n");
      out.write("                    </ul>\n");
      out.write("                </div>\n");
      out.write("                ");
 } else {
      out.write("\n");
      out.write("                <!-- Login and Register buttons for non-logged-in users -->\n");
      out.write("                <div>\n");
      out.write("                    <form>\n");
      out.write("                        <button type=\"submit\" name=\"button\" value=\"Login\" class=\"btn btn-login\" formaction=\"login2.jsp\">Login</button>\n");
      out.write("                        <button type=\"submit\" name=\"button\" value=\"Register\" class=\"btn btn-danger\" formaction=\"register.jsp\">Register</button>\n");
      out.write("                    </form>\n");
      out.write("                </div>\n");
      out.write("                ");
 }
                
      out.write("\n");
      out.write("            </nav>\n");
      out.write("        </header>\n");
      out.write("    </body>\n");
      out.write("</html>\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("        <title>JSP Page</title>\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/login.css\" type=\"text/css\">\n");
      out.write("        <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\" \n");
      out.write("              integrity=\"sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN\" crossorigin=\"anonymous\">\n");
      out.write("\n");
      out.write("    </head>\n");
      out.write("    <style>\n");
      out.write("        @import url('https://fonts.googleapis.com/css2?family=Sriracha&display=swap');\n");
      out.write("        .logo {\n");
      out.write("                font-size: 25px;\n");
      out.write("                font-family: 'Sriracha', cursive;\n");
      out.write("                color: #000;\n");
      out.write("                text-decoration: none;\n");
      out.write("                margin-left: 30px;\n");
      out.write("            }\n");
      out.write("    </style>\n");
      out.write("    <body>\n");
      out.write("        <section class=\"h-100 gradient-form\" style=\"background-color: #eee;\">\n");
      out.write("          <div class=\"container py-5 h-100\">\n");
      out.write("            <div class=\"row d-flex justify-content-center align-items-center h-100\">\n");
      out.write("              <div class=\"col-xl-10\">\n");
      out.write("                <div class=\"card rounded-3 text-black\">\n");
      out.write("                  <div class=\"row g-0\">\n");
      out.write("                    <div class=\"col-lg-6\">\n");
      out.write("                      <div class=\"card-body p-md-5 mx-md-4\">\n");
      out.write("\n");
      out.write("                        <div class=\"text-center\">\n");
      out.write("                          <h3 class=\"mt-1 mb-5 pb-1\"><a href=\"#\" class=\"logo\">Developer</a></h3 >\n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("                          <form action=\"login\" method=\"post\">\n");
      out.write("                          <p>Please login to your account</p>\n");
      out.write("\n");
      out.write("                          <div class=\"form-floating mb-3\">\n");
      out.write("                              <input type=\"text\" class=\"form-control\" id=\"floatingInput\" placeholder=\"Your username or email\" name=\"user\">\n");
      out.write("                            <label for=\"floatingInput\">Username</label>\n");
      out.write("                          </div>\n");
      out.write("                          <div class=\"form-floating\">\n");
      out.write("                              <input type=\"password\" class=\"form-control\" id=\"floatingPassword\" placeholder=\"Your password\" name=\"pass\">\n");
      out.write("                            <label for=\"floatingPassword\">Password</label>\n");
      out.write("                          </div>\n");
      out.write("\n");
      out.write("                          <div class=\"text-center pt-1 mb-5 pb-1\">\n");
      out.write("                            <button class=\"btn btn-primary btn-block fa-lg gradient-custom-2 pt-1 mb-3 pb-1\" id=\"button\" type=\"summit\">Log\n");
      out.write("                                in</button> <br>\n");
      out.write("                                <a class=\"text-muted\" href=\"resetpass.jsp\">Forgot password?</a>\n");
      out.write("                          </div>\n");
      out.write("\n");
      out.write("                          <div class=\"d-flex align-items-center justify-content-center pb-4\">\n");
      out.write("                            <p class=\"mb-0 me-2\">Don't have an account?</p>\n");
      out.write("                            <button type=\"summit\" class=\"btn btn-outline-danger\" formaction=\"signup.jsp\">Create new</button>\n");
      out.write("                          </div>\n");
      out.write("\n");
      out.write("                        </form>\n");
      out.write("\n");
      out.write("                      </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col-lg-6 d-flex align-items-center gradient-custom-2\">\n");
      out.write("                      <div class=\"text-black px-3 py-4 p-md-5 mx-md-4\">\n");
      out.write("                        <h4 class=\"mb-4\">Nothing here</h4>\n");
      out.write("                        <p class=\"small mb-0\">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n");
      out.write("                          tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud\n");
      out.write("                          exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>\n");
      out.write("                      </div>\n");
      out.write("                    </div>\n");
      out.write("                  </div>\n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("        </section>\n");
      out.write("    </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
